name: Publish temporary tag

on:
  push:
    paths:
      - ".github/workflows/publish-temp-release.yml"

permissions:
  contents: write

jobs:
  tag:
    if: github.event.head_commit.message == 'chore: publish tag v1.6.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v1.6.0" "443df25269e737625d26ac4ad09b3879580f6a81"
          git push origin "v1.6.0"
